# Generated by Django 2.2.16 on 2021-11-09 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20211109_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, max_length=150, verbose_name='Role'),
        ),
    ]
