# Generated by Django 2.2.16 on 2021-11-08 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.TextField(blank=True, verbose_name='Token'),
        ),
    ]
